# Generated by Django 5.2 on 2025-04-17 21:17

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_flight_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.airplane_image_file_path
            ),
        ),
    ]
